# Generated by Django 6.0.5 on 2026-08-30 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=12, unique=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('encaminhada', 'Encaminhada ao CAE'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='usuarios.usuarios')),
                ('tipo_violencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='denuncias.tipoviolencia')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('formato', models.CharField(max_length=20)),
                ('dados', models.ImageField(upload_to='evidencias/')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='denuncias.denuncia')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_dadas', to='usuarios.usuarios')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='denuncias.denuncia')),
            ],
        ),
    ]
