# Generated by Django 6.0.5 on 2026-09-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=12, unique=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('encaminhada', 'Encaminhada ao CAE'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('data_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('formato', models.CharField(max_length=20)),
                ('dados', models.ImageField(upload_to='evidencias/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
