# Generated by Django 6.0.5 on 2026-09-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='denunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='denuncias.denuncia'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tipo_violencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='denuncias.tipoviolencia'),
        ),
    ]
