# Generated by Django 6.0.5 on 2026-09-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='protocolo',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
