# Generated by Django 6.0.5 on 2026-09-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('direitos', 'Direitos'), ('prevencao', 'Prevenção'), ('impactos', 'Impactos psicológicos')], max_length=20)),
                ('corpo', models.TextField()),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
