# Generated by Django 6.0.5 on 2026-09-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conteudos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoeducativo',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='conteudoeducativo',
            name='canais_apoio',
            field=models.ManyToManyField(blank=True, related_name='conteudos', to='conteudos.canalapoio'),
        ),
    ]
