# Generated by Django 6.0.5 on 2026-09-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncias', '0002_initial'),
        ('respostas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostadenuncia',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_dadas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='respostadenuncia',
            name='denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='denuncias.denuncia'),
        ),
    ]
